name: Bogazici-DevSecOps-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}   # İstersen Actions > Run workflow ile manuel tetikleyebil

jobs:
  build-and-syft:
    name: Build & SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker imajını mevcut Dockerfile ile build et
      - name: Build Docker image
        run: |
          docker build -t juice-shop:${{ github.sha }} .

      # Syft ile imajdan SPDX SBOM üret
      - name: Syft SBOM Scan (image → SPDX)
        uses: anchore/sbom-action@v0
        with:
          image: "juice-shop:${{ github.sha }}"
          format: "spdx-json"
          output-file: "sbom.spdx.json"
