# 2) SAST (Semgrep) Job — ekrandaki formatla aynı
  sast-scan:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    container: returntocorp/semgrep:latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Semgrep Scan
        run: |
          mkdir -p semgrep/results
          semgrep ci --config=auto --sarif --output=semgrep/results/semgrep.sarif || true

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'semgrep/results/semgrep.sarif'

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: semgrep-results
          path: semgrep/results/

  # 3) Secrets (Gitleaks) Job — İSTEDİĞİN EKLEME
  secrets-scan:
    name: Secrets (Gitleaks)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare results dir
        run: mkdir -p gitleaks/results

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        with:
          # raporu SARIF üret, Code scanning'e uygun olsun
          args: --no-git -v --redact --report-format sarif --report-path gitleaks/results/gitleaks.sarif

      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: gitleaks/results/gitleaks.sarif

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-results
          path: gitleaks/results/
